kind: Service
apiVersion: v1
metadata:
  namespace: kubernetes-live
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181